// <auto-generated />
using System;
using Ajial.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ajial.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ajial.Domain.Entities.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BloodType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ChildLoginId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("HasCompletedAdditionalVaccinationSurvey")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCompletedVaccinationSurvey")
                        .HasColumnType("bit");

                    b.Property<double?>("HeadCircumference")
                        .HasColumnType("float");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalHistory")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ChildLoginId")
                        .IsUnique()
                        .HasFilter("[ChildLoginId] IS NOT NULL");

                    b.HasIndex("IsActive");

                    b.HasIndex("ParentId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("Ajial.Domain.Entities.ChildVaccination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VaccinationMilestoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("VaccinationMilestoneId");

                    b.HasIndex("ChildId", "VaccinationMilestoneId")
                        .IsUnique();

                    b.ToTable("ChildVaccinations");
                });

            modelBuilder.Entity("Ajial.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Cairo",
                            NameAr = "القاهرة"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Alexandria",
                            NameAr = "الإسكندرية"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Giza",
                            NameAr = "الجيزة"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Shubra El Kheima",
                            NameAr = "شبرا الخيمة"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Port Said",
                            NameAr = "بورسعيد"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Suez",
                            NameAr = "السويس"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Mansoura",
                            NameAr = "المنصورة"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "El Mahalla El Kubra",
                            NameAr = "المحلة الكبرى"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Tanta",
                            NameAr = "طنطا"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Asyut",
                            NameAr = "أسيوط"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Fayyum",
                            NameAr = "الفيوم"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Zagazig",
                            NameAr = "الزقازيق"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Ismailia",
                            NameAr = "الإسماعيلية"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Aswan",
                            NameAr = "أسوان"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "6th of October City",
                            NameAr = "السادس من أكتوبر"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "Damanhur",
                            NameAr = "دمنهور"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "Damietta",
                            NameAr = "دمياط"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Name = "Minya",
                            NameAr = "المنيا"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            Name = "Beni Suef",
                            NameAr = "بني سويف"
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            Name = "Luxor",
                            NameAr = "الأقصر"
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            Name = "Sohag",
                            NameAr = "سوهاج"
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            Name = "Shibin El Kom",
                            NameAr = "شبين الكوم"
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            Name = "Qena",
                            NameAr = "قنا"
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            Name = "Hurghada",
                            NameAr = "الغردقة"
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            Name = "Arish",
                            NameAr = "العريش"
                        },
                        new
                        {
                            Id = 26,
                            IsActive = true,
                            Name = "Mallawi",
                            NameAr = "ملوي"
                        },
                        new
                        {
                            Id = 27,
                            IsActive = true,
                            Name = "10th of Ramadan City",
                            NameAr = "العاشر من رمضان"
                        },
                        new
                        {
                            Id = 28,
                            IsActive = true,
                            Name = "Bilbais",
                            NameAr = "بلبيس"
                        },
                        new
                        {
                            Id = 29,
                            IsActive = true,
                            Name = "Marsa Matruh",
                            NameAr = "مرسى مطروح"
                        },
                        new
                        {
                            Id = 30,
                            IsActive = true,
                            Name = "Banha",
                            NameAr = "بنها"
                        },
                        new
                        {
                            Id = 31,
                            IsActive = true,
                            Name = "Kafr El Sheikh",
                            NameAr = "كفر الشيخ"
                        },
                        new
                        {
                            Id = 32,
                            IsActive = true,
                            Name = "Sharm El Sheikh",
                            NameAr = "شرم الشيخ"
                        },
                        new
                        {
                            Id = 33,
                            IsActive = true,
                            Name = "New Cairo",
                            NameAr = "القاهرة الجديدة"
                        },
                        new
                        {
                            Id = 34,
                            IsActive = true,
                            Name = "New Administrative Capital",
                            NameAr = "العاصمة الإدارية الجديدة"
                        });
                });

            modelBuilder.Entity("Ajial.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationTokens");
                });

            modelBuilder.Entity("Ajial.Domain.Entities.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("Ajial.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Ajial.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ajial.Domain.Entities.VaccinationMilestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeInMonths")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Main");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("VaccinesAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("VaccinesEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("VaccinationMilestones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeInMonths = 0,
                            Category = "Main",
                            IsActive = true,
                            NameAr = "تطعيم الولادة",
                            NameEn = "Birth Vaccination",
                            SortOrder = 1,
                            VaccinesAr = "كبدي ب رضع, شلل اطفال فموي, طعم بي سي جي",
                            VaccinesEn = "Hepatitis B, Oral Polio Vaccine, BCG"
                        },
                        new
                        {
                            Id = 2,
                            AgeInMonths = 2,
                            Category = "Main",
                            IsActive = true,
                            NameAr = "تطعيم شهرين",
                            NameEn = "2 Months Vaccination",
                            SortOrder = 2,
                            VaccinesAr = "شلل اطفال (فموي), الطعم الخماسي",
                            VaccinesEn = "Oral Polio Vaccine, Pentavalent Vaccine"
                        },
                        new
                        {
                            Id = 3,
                            AgeInMonths = 4,
                            Category = "Main",
                            IsActive = true,
                            NameAr = "تطعيم 4 شهور",
                            NameEn = "4 Months Vaccination",
                            SortOrder = 3,
                            VaccinesAr = "شلل اطفال (فموي), الطعم الخماسي, شلل اطفال (حقن)",
                            VaccinesEn = "Oral Polio Vaccine, Pentavalent Vaccine, IPV"
                        },
                        new
                        {
                            Id = 4,
                            AgeInMonths = 6,
                            Category = "Main",
                            IsActive = true,
                            NameAr = "تطعيم 6 شهور",
                            NameEn = "6 Months Vaccination",
                            SortOrder = 4,
                            VaccinesAr = "شلل اطفال (فموي), الطعم الخماسي, شلل اطفال (حقن)",
                            VaccinesEn = "Oral Polio Vaccine, Pentavalent Vaccine, IPV"
                        },
                        new
                        {
                            Id = 5,
                            AgeInMonths = 9,
                            Category = "Main",
                            IsActive = true,
                            NameAr = "تطعيم 9 شهور",
                            NameEn = "9 Months Vaccination",
                            SortOrder = 5,
                            VaccinesAr = "شلل اطفال (فموي)",
                            VaccinesEn = "Oral Polio Vaccine"
                        },
                        new
                        {
                            Id = 6,
                            AgeInMonths = 12,
                            Category = "Main",
                            IsActive = true,
                            NameAr = "تطعيم 12 شهر",
                            NameEn = "12 Months Vaccination",
                            SortOrder = 6,
                            VaccinesAr = "شلل اطفال (فموي), الثلاثى الفيروسي",
                            VaccinesEn = "Oral Polio Vaccine, MMR"
                        },
                        new
                        {
                            Id = 7,
                            AgeInMonths = 18,
                            Category = "Main",
                            IsActive = true,
                            NameAr = "تطعيم 18 شهر",
                            NameEn = "18 Months Vaccination",
                            SortOrder = 7,
                            VaccinesAr = "شلل اطفال (فموي), الثلاثى الفيروسي",
                            VaccinesEn = "Oral Polio Vaccine, MMR"
                        },
                        new
                        {
                            Id = 8,
                            AgeInMonths = 48,
                            Category = "Additional",
                            IsActive = true,
                            NameAr = "تطعيم أولى حضانة",
                            NameEn = "KG1 Vaccination",
                            SortOrder = 8,
                            VaccinesAr = "المكورات السحائية الثنائى",
                            VaccinesEn = "Meningococcal Vaccine"
                        },
                        new
                        {
                            Id = 9,
                            AgeInMonths = 72,
                            Category = "Additional",
                            IsActive = true,
                            NameAr = "تطعيم أولى ابتدائى",
                            NameEn = "Grade 1 Vaccination",
                            SortOrder = 9,
                            VaccinesAr = "المكورات السحائية الثنائى",
                            VaccinesEn = "Meningococcal Vaccine"
                        },
                        new
                        {
                            Id = 10,
                            AgeInMonths = 84,
                            Category = "Additional",
                            IsActive = true,
                            NameAr = "تطعيم ثانية ابتدائى",
                            NameEn = "Grade 2 Vaccination",
                            SortOrder = 10,
                            VaccinesAr = "الثنائى البكتيري",
                            VaccinesEn = "DT Vaccine"
                        },
                        new
                        {
                            Id = 11,
                            AgeInMonths = 120,
                            Category = "Additional",
                            IsActive = true,
                            NameAr = "تطعيم رابعة ابتدائى",
                            NameEn = "Grade 4 Vaccination",
                            SortOrder = 11,
                            VaccinesAr = "الثنائى البكتيري",
                            VaccinesEn = "DT Vaccine"
                        },
                        new
                        {
                            Id = 12,
                            AgeInMonths = 144,
                            Category = "Additional",
                            IsActive = true,
                            NameAr = "تطعيم أولى إعدادي",
                            NameEn = "Grade 7 Vaccination",
                            SortOrder = 12,
                            VaccinesAr = "المكورات السحائية الثنائى",
                            VaccinesEn = "Meningococcal Vaccine"
                        },
                        new
                        {
                            Id = 13,
                            AgeInMonths = 180,
                            Category = "Additional",
                            IsActive = true,
                            NameAr = "تطعيم أولى ثانوي",
                            NameEn = "Grade 10 Vaccination",
                            SortOrder = 13,
                            VaccinesAr = "المكورات السحائية الثنائى",
                            VaccinesEn = "Meningococcal Vaccine"
                        });
                });

            modelBuilder.Entity("Ajial.Domain.Entities.VoiceNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.ToTable("VoiceNotes");
                });

            modelBuilder.Entity("Ajial.Domain.Entities.Child", b =>
                {
                    b.HasOne("Ajial.Domain.Entities.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Ajial.Domain.Entities.ChildVaccination", b =>
                {
                    b.HasOne("Ajial.Domain.Entities.Child", "Child")
                        .WithMany("Vaccinations")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ajial.Domain.Entities.VaccinationMilestone", "VaccinationMilestone")
                        .WithMany()
                        .HasForeignKey("VaccinationMilestoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("VaccinationMilestone");
                });

            modelBuilder.Entity("Ajial.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("Ajial.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ajial.Domain.Entities.Parent", b =>
                {
                    b.HasOne("Ajial.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ajial.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Ajial.Domain.Entities.Parent", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ajial.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Ajial.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ajial.Domain.Entities.VoiceNote", b =>
                {
                    b.HasOne("Ajial.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Ajial.Domain.Entities.Child", b =>
                {
                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("Ajial.Domain.Entities.Parent", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
