namespace Ajial.Application.DTOs.VaccinationReminder;

/// <summary>
/// Sent by the Flutter app after Firebase.initializeApp() + FirebaseMessaging.instance.getToken()
/// to register/update the current phone's push notification token.
/// </summary>
public class RegisterDeviceTokenRequest
{
    /// <summary>The FCM registration token generated by the Flutter firebase_messaging plugin.</summary>
    public string DeviceToken { get; set; } = string.Empty;
}
