name: Ajial
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dropdown_search: ^5.0.6
  intl: ^0.20.2
  pinput: ^4.0.0
  dio: ^5.1.0
  flutter_secure_storage: ^8.0.0
  flutter_localizations:
    sdk: flutter
  http: ^1.6.0
  http_parser: ^4.0.2
  shared_preferences: ^2.5.3
  provider: ^6.1.2
  audioplayers: ^6.5.1
  record: ^5.2.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2 # (تحديث للنسخة الأحدث)
  path: ^1.9.0 # (تحديث)
  mime: ^2.0.0 # (تحديث) # (اختياري للتعامل مع أنواع الملفات)
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  firebase_core: ^4.5.0
  firebase_messaging: ^16.1.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_timezone: ^3.0.1
  alarm: ^5.2.1
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  web: ^1.1.0
  file_picker: ^11.0.2
  pdf: ^3.11.1
  printing: ^5.13.4
  gal: ^2.3.1
  open_file: ^3.5.11
  signalr_netcore: ^1.3.7 # Real-time consultation chat (SignalR client)

dependency_overrides:
  record_linux: ^1.2.1
  record_platform_interface: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  confetti: ^0.7.0
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/consultations/
    - assets/sounds/
  fonts:
    - family: IBM Plex Sans Arabic
      fonts:
        - asset: fonts/IBMPlexSansArabic-Regular.ttf
        - asset: fonts/IBMPlexSansArabic-Bold.ttf
        - asset: fonts/IBMPlexSansArabic-ExtraLight.ttf
        - asset: fonts/IBMPlexSansArabic-Light.ttf
        - asset: fonts/IBMPlexSansArabic-Medium.ttf
        - asset: fonts/IBMPlexSansArabic-SemiBold.ttf
        - asset: fonts/IBMPlexSansArabic-Thin.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#BF092F"
  adaptive_icon_foreground: "images/logo.png"
